export const frenchToEnglishColors = {
    "rouge": "red",
    "bleu": "blue",
    "vert": "green",
    "jaune": "yellow",
    "noir": "black",
    "blanc": "white",
    "gris": "gray",
    "gris clair": "lightgray",
    "gris foncé": "darkgray",
    "rose": "pink",
    "rose clair": "lightpink",
    "rose foncé": "deeppink",
    "violet": "purple",
    "violet clair": "lavender",
    "violet foncé": "indigo",
    "mauve": "mediumorchid",
    "lavande": "lavender",
    "orange": "orange",
    "orange foncé": "darkorange",
    "orange clair": "lightsalmon",
    "brun": "brown",
    "marron": "saddlebrown",
    "chocolat": "chocolate",
    "cuivre": "peru",
    "ocre": "darkgoldenrod",
    "beige": "beige",
    "ivoire": "ivory",
    "crème": "cornsilk",
    "or": "gold",
    "argent": "silver",
    "cyan": "cyan",
    "turquoise": "turquoise",
    "turquoise clair": "lightseagreen",
    "turquoise foncé": "darkturquoise",
    "bleu clair": "lightblue",
    "bleu ciel": "skyblue",
    "bleu foncé": "darkblue",
    "bleu marine": "navy",
    "vert clair": "lightgreen",
    "vert foncé": "darkgreen",
    "vert olive": "olive",
    "vert forêt": "forestgreen",
    "vert menthe": "mediumseagreen",
    "vert citron": "greenyellow",
    "jaune clair": "lightyellow",
    "jaune foncé": "goldenrod",
    "saumon": "salmon",
    "corail": "coral",
    "bordeaux": "maroon",
    "aubergine": "rebeccapurple",
    "pêche": "peachpuff",
    "abricot": "bisque",
    "tomate": "tomato",
    "caramel": "sandybrown",
    "bleu pétrole": "teal",
    "bleu azur": "deepskyblue",
    "indigo": "indigo",
    "fuchsia": "fuchsia",
    "magenta": "magenta",
    "améthyste": "mediumslateblue",
    "saphir": "royalblue",
    "émeraude": "seagreen",
    "topaze": "khaki",
    "rubis": "crimson",
    "ardoise": "slategray",
    "charbon": "dimgray",
    "nude": "linen",
    "café": "rosybrown",
    "kaki": "darkkhaki",
    "moutarde": "darkkhaki",
    "menthe": "mintcream",
    "anis": "palegreen",
    "taupe": "tan",
    "terracotta": "indianred",
    "ciel": "lightskyblue",
    "neige": "snow",
    "vieux rose": "palevioletred"
};
